# Generated by Django 5.2.7 on 2025-10-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('year_level', models.IntegerField()),
            ],
        ),
    ]
